# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		crc_test
SRCS+=		crc_test.c
SRCS+=		${PFL_BASE}/psc_util/crc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c

include ${PFLMK}
