# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		base64_test
SRCS+=		base64_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/base64.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c

include ${PFLMK}
