# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		hashtbl_test
SRCS+=		hashtbl_test.c
SRCS+=		${PFL_BASE}/psc_ds/hashtbl.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c

include ${PFLMK}
