# $Id: $

ROOTDIR = ..
include ${ROOTDIR}/mk/defs.mk

LIBRARY=	libpsc_util.a
SRCS=	crc.c
SRCS+=	log.c
SRCS+=	myrandom.c
SRCS+=	palloc.c
SRCS+=	pthread_barrier.c
#SRCS+=	semaphore.c
SRCS+=	subsys.c
SRCS+=	thread.c
SRCS+=	threadtable.c
SRCS+=	waitq.c

include	${MAINMK}

#CFLAGS+= -O2

