# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		alloc_test
SRCS+=		alloc_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c

MODULES+=	pfl str

include ${PFLMK}
