# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		alloc_test
SRCS+=		alloc_test.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c

MODULES+=	pfl str

include ${PFLMK}
