# $Id$
# %PSC_COPYRIGHT%

LNET_BASE=	${ROOTDIR}/lnet-lite
PFL_BASE=	${ROOTDIR}/pfl

MAINMK=		${ROOTDIR}/mk/main.mk
PFLMK=		${PFL_BASE}/mk/main.mk

-include ${ROOTDIR}/distrib/*/mk/dep.mk
AA:=$(shell ls -l ${ROOTDIR}/*/mk/dep.mk >&2)
-include ${ROOTDIR}/*/mk/dep.mk
