.\" $Id$
.\" %ISC_START_LICENSE%
.\" ---------------------------------------------------------------------
.\" Copyright 2013-2015, Pittsburgh Supercomputing Center
.\" All rights reserved.
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the
.\" above copyright notice and this permission notice appear in all
.\" copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
.\" PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.\" --------------------------------------------------------------------
.\" %END_LICENSE%
.Dd June 19, 2015
.Dt SFT 1
.ds volume PSC \- User Reference Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm sft
.Nd \&"Swiss army" file tool
.Sh SYNOPSIS
.Nm sft
.Bk -words
.Op Fl BcdKPRvwZ
.Op Fl b Ar bufsz
.Op Fl O Ar offset
.Op Fl s Ar size
.Op Fl t Ar nthr
.Ar
.Ek
.Sh DESCRIPTION
The
.Nm
utility provides a few handy capabilities for file I/O.
It can read, checksum, and write data and can provide basic performance
metrics about the activity it performs.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl B
Display a bandwidth meter during progress.
.It Fl b Ar bufsz
Change the default file chunk size to
.Ar bufsz .
Defaults to 32768.
.It Fl c
Compute and display a checksum over the entire file contents.
.It Fl d
Use direct I/O
.Pq Li O_DIRECT
for read or write I/O.
.It Fl K
When used with
.Fl K ,
display checksums of each file chunk
.Pq to control chunk size, see Fl b .
.It Fl O Ar offset
Start processing each specified file at the given
.Ar offset .
.It Fl P
Perform piecewise processing of each file specified on the command line.
The default behavior is to perform processing sequentially until
completion of each file specified instead of round-robin processing.
.It Fl R
Recursively process all files and subdirectories in any directories
specified on the command line.
.It Fl s Ar size
Specify the total I/O
.Ar size
to perform on each file specified on the command line.
.It Fl t Ar nthr
Specify the number of processing threads that should perform I/O on each
file.
Defaults to 1.
.It Fl v
Verbosely display ongoing operations.
.It Fl w
Perform write operation over the file contents with random junk.
The default amount of data to write is the current existing file size
which may be overridden with the
.Fl s
option.
The default operation is to read file contents.
.It Fl Z
Check if a file chunk is composed of entirely zeroes and display
a indicator
.Pq Sq Z
for any such chunks
.Pq see Fl K .
Defaults to 32768.
.El
.\" .El
.\" .Sh ENVIRONMENT
.\" pfl env
.\" .Bl -tag -width Ev
.\" .El
.Sh SEE ALSO
.Xr dd 1
