.\" $Id$
.\" %PSC_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2013-2014, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, modify, and distribute this software
.\" for any purpose with or without fee is hereby granted, provided
.\" that the above copyright notice and this permission notice
.\" appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL
.\" THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
.\" CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
.\" LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
.\" NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
.\" CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" Pittsburgh Supercomputing Center	phone: 412.268.4960  fax: 412.268.5832
.\" 300 S. Craig Street			e-mail: remarks@psc.edu
.\" Pittsburgh, PA 15213			web: http://www.psc.edu/
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd December 17, 2012
.Dt XOPCTL 1
.ds volume PSC \- User Reference Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm sft
.Nd swissarmy file transfer tool
.Sh SYNOPSIS
.Nm xopctl
.Bk -words
.Op Fl BcKRvwZ
.Op Fl b Ar bufsz
.Op Fl t Ar nthr
.Op Fl O Ar offset
.Ar
.Ek
.Sh DESCRIPTION
The
.Nm
utility provides a few handy capabilities for file I/O.
It can read, checksum, and write data and provide basic performance
metrics about the activity.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl B
Display a bandwidth meter during progress.
.It Fl b Ar bufsz
Change the default file chunk size to
.Ar bufsz .
.It Fl c
Compute and display a checksum over the entire file contents.
.It Fl K
When used with
.Fl K ,
display checksums of each file chunk
.Pq to control chunk size, see Fl b .
.It Fl O Ar offset
Start processing each specified file at the given
.Ar offset .
.It Fl R
Recursively process all files and subdirectories in any directories
specified on the command line.
.It Fl t Ar nthr
Specify the number of processing threads that should perform I/O on each
file.
Defaults to 1.
.It Fl v
Verbosely display ongoing operations.
.It Fl w Ar size
Perform
.Xr write 2
of junk data over any files specified on the command line to the given
.Ar size .
.It Fl Z
Check if a file chunk is composed of entirely zeroes and display
a indicator
.Pq Sq Z
for any such chunks
.Pq see Fl K .
Defaults to 32768.
.El
.\" .El
.\" .Sh ENVIRONMENT
.\" pfl env
.\" .Bl -tag -width Ev
.\" .El
.Sh SEE ALSO
.Xr dd 1
