# $Id$

ifeq ($(filter $(realpath ${ROOTDIR})/compat/%,${CURDIR}),)

PICKLELOCALMK=${ROOTDIR}/mk/gen-localdefs-pickle.mk

-include ${PICKLELOCALMK}

PICKLE_NEED_VERSION=		1

ifneq (${PICKLE_NEED_VERSION},${PICKLE_HAS_VERSION})
 $(shell echo "# generated by `whoami` on `date`" > ${PICKLELOCALMK})
 $(shell echo "PICKLE_HAS_VERSION=${PICKLE_NEED_VERSION}" >> ${PICKLELOCALMK})

 $(shell cd ${ROOTDIR}/compat/posix_memalign && ${QMAKE} &&		\
    echo "PICKLE_HAVE_POSIX_MEMALIGN=1" >> ${PICKLELOCALMK})

 $(shell cd ${ROOTDIR}/compat/pthread_mutex_timedlock && ${QMAKE} &&	\
    echo "PICKLE_HAVE_PTHREAD_MUTEX_TIMEDLOCK=1" >> ${PICKLELOCALMK})

 $(shell cd ${ROOTDIR}/compat/clock_gettime && ${QMAKE} &&		\
    echo "PICKLE_HAVE_CLOCK_GETTIME=1" >> ${PICKLELOCALMK})

 $(shell cd ${ROOTDIR}/compat/host_name_max && ${QMAKE} &&		\
    echo "PICKLE_HAVE_HOST_NAME_MAX=1" >> ${PICKLELOCALMK})

 include ${PICKLELOCALMK}
endif

endif
