.\" $Id$
.\" This file belongs to the public domain.
.Dd July 23, 2004
.Dt PSIG 1
.Os
.Sh NAME
.Nm psig
.Nd print signal actions of processes
.Sh SYNOPSIS
.Nm psig
.Op Fl h
.Ar pid ...
.Sh DESCRIPTION
The
.Nm
utility displays the actions that will be taken upon reception of
signals for the given processes.
It also shows the number of pending signals waiting to be delivered
for each signal type.
Processes are specified by
.Ar pid
arguments, which are process IDs.
.Pp
The following options are supported:
.Bl -tag -width Ds
.It Fl h
Print the symbol name of the handler concurrently assigned to
each signal.
.El
.Pp
The
.Nm
utility exits zero on success or with one of the
.Xr sysexits 3
error codes on failure.
.Sh SEE ALSO
.Xr sigaction 2
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
