# $Id$

include ../Makefile.path

PROG=		prsig
SRCS=		prsig.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/prsig.c
SRCS+=		${PFL_BASE}/psc_util/strlcat.c

include ${PFLMK}
