# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		prsig_test
SRCS+=		prsig_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/prsig.c
SRCS+=		${PFL_BASE}/psc_util/strlcat.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

include ${PFLMK}
