# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		lnrtctl
FORCE_INST=	1
MAN+=		lnrtctl.8
SRCS+=		lnrtctl.c
SRCS+=		${PFL_BASE}/ctlcli.c

MODULES+=	lnet-hdrs pthread pfl curses

include ${PFLMK}
