# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		dynarray_test
SRCS+=		dynarray_test.c
SRCS+=		${PFL_BASE}/dynarray.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c

include ${PFLMK}
