# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		vbitmap_test
SRCS+=		vbitmap_test.c
SRCS+=		${PFL_BASE}/psc_ds/vbitmap.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

include ${PFLMK}
