# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		refmgr_test
SRCS+=		refmgr_test.c
SRCS+=		${PFL_BASE}/psc_ds/dynarray.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/hash2.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/pool.c
SRCS+=		${PFL_BASE}/psc_util/refmgr.c
SRCS+=		${PFL_BASE}/psc_util/waitq.c

include ${PFLMK}
