# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		refmgr_test
SRCS+=		refmgr_test.c
SRCS+=		${PFL_BASE}/dynarray.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/hashtbl.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/pool.c
SRCS+=		${PFL_BASE}/refmgr.c
SRCS+=		${PFL_BASE}/waitq.c

include ${PFLMK}
