include ${ROOTDIR}/mk/local.mk

MAINMK = ${ROOTDIR}/mk/main.mk

LNET_BASE =	${ROOTDIR}/lnet-lite

DEFINES+=	-DHAVE_LIBPTHREAD 
DEFINES+=	-DHAVE_GETHOSTBYNAME_DEFINED 
DEFINES+=	-DHAVE_GETHOSTBYNAME 
DEFINES+=	-DHAVE_LIBPTHREAD_DEFINED 
DEFINES+=	-DPSC_LNET

INCLUDES += -I. -I${ROOTDIR}/include
CFLAGS += -Wall -W -g ${INCLUDES} ${DEFINES}
YFLAGS += -d -o $@
