# $Id$

DEFINES+=	-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DLINUX
INCLUDES+=	-I${ZEST_BASE}/include/kernel/2.6.9-42.0.8.EL_lustre.1.4.9.1/include/
INCLUDES+=	-I${KERNEL_BASE}/include

THREAD_LIBS?=	-lpthread
