# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		meter_test
SRCS+=		meter_test.c
SRCS+=		${PFL_BASE}/ctlcli.c
SRCS+=		${PFL_BASE}/fmt.c
SRCS+=		${PFL_BASE}/pthrutil.c
SRCS+=		${PFL_BASE}/thread.c
SRCS+=		${PFL_BASE}/vbitmap.c
MODULES+=	lnet-hdrs pthread

include ${PFLMK}
