# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		rtgetif
SRCS=		rtgetif.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/netutil.c

include ${PFLMK}
