# $Id$

include Makefile.path

SUBDIRS+=	acsvc
SUBDIRS+=	atomic
SUBDIRS+=	bitflag
SUBDIRS+=	fmtstr
SUBDIRS+=	hash2
SUBDIRS+=	lock
SUBDIRS+=	lock2
SUBDIRS+=	multilock
SUBDIRS+=	prsig
SUBDIRS+=	random
SUBDIRS+=	rwlock
SUBDIRS+=	setprocesstitle
SUBDIRS+=	sig
SUBDIRS+=	vbitmap
SUBDIRS+=	waitq

include ${PFLMK}
