# $Id$

include Makefile.path

SUBDIRS+=	acsvc
SUBDIRS+=	atomic
SUBDIRS+=	bitflag
SUBDIRS+=	bw
SUBDIRS+=	fmtstr
SUBDIRS+=	lock
SUBDIRS+=	random
SUBDIRS+=	sig
SUBDIRS+=	vbitmap
SUBDIRS+=	waitq

include ${PFLMK}
