# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		rtgetif
SRCS=		rtgetif.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/netutil.c

include ${PFLMK}
