# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		fmt_test
SRCS+=		fmt_test.c
SRCS+=		${PFL_BASE}/psc_util/fmt.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/str.c
MODULES+=	pfl

include ${PFLMK}
