# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		fmt_test
SRCS+=		fmt_test.c
SRCS+=		${PFL_BASE}/fmt.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/str.c
MODULES+=	pfl

include ${PFLMK}
