# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		hash2_test
SRCS+=		hash2_test.c
SRCS+=		${PFL_BASE}/psc_ds/hash2.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

include ${PFLMK}
