# $Id$

include ../Makefile.path

PROG=		zestWaitqTest
SRCS=		zestWaitqTest.c
SRCS+=		../../zestion/log.c
SRCS+=		../../zestion/thread.c
SRCS+=		../../zestion/zestHash.c
SRCS+=		../../zestion/zestThreadTable.c
SRCS+=		../../zestion/zestWaitq.c
LDFLAGS+=	${THREAD_LIBS}

include ${ZESTMK}
