# $Id$

LLROOTDIR=.
include Makefile.path
include ${LLMK}

# We can't specify SUBDIRS here; it instead must be specified on
# the command line to make(1) for each case (e.g. when building
# clients and server), since it differs for each.
