# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		multiwait_test
SRCS+=		multiwait_test.c
SRCS+=		${PFL_BASE}/dynarray.c
SRCS+=		${PFL_BASE}/vbitmap.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/multiwait.c
SRCS+=		${PFL_BASE}/pthrutil.c

MODULES+=	pthread

include ${PFLMK}
