# $Id$

include ../Makefile.path

PROG=		atomic_test
SRCS+=		atomic_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c

MODULES+=	pthread

include ${PFLMK}
