.\" $Id$
.\" %ISC_START_LICENSE%
.\" ---------------------------------------------------------------------
.\" Copyright 2015-2016, Google, Inc.
.\" Copyright (c) 2013-2015, Pittsburgh Supercomputing Center (PSC).
.\" All rights reserved.
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the
.\" above copyright notice and this permission notice appear in all
.\" copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
.\" WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL THE
.\" AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
.\" DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
.\" PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.\" --------------------------------------------------------------------
.\" %END_LICENSE%
.Dd August 17, 2013
.Dt PFL.MK 5
.ds volume PSC \- Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm pfl.mk
.Nd P file system library make directives
.Sh SYNOPSIS
.Bd -literal
ROOTDIR=../..
include ${ROOTDIR}/Makefile.path
\&...
include ${PFLMK}
.Ed
.Sh DESCRIPTION
The
.Nm pfl.mk
.El
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa /etc/foo
resource configuration
.El
.Sh EXAMPLES
The following is an example
.Nm slcfg :
.Bd -literal
		id	= 400;
		nid	= 67.171.74.150;
	}
}
.Ed
.Sh SEE ALSO
.Xr mount_slash 8 ,
