# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		dynarray_test
SRCS+=		dynarray_test.c
SRCS+=		${PFL_BASE}/psc_ds/dynarray.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c

include ${PFLMK}
