# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		hashtbl_test
SRCS+=		hashtbl_test.c
SRCS+=		${PFL_BASE}/hashtbl.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c

include ${PFLMK}
