# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		alloc_test
SRCS+=		alloc_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

include ${PFLMK}
