# $Id$

ROOTDIR=../..
include ${ROOTDIR}/Makefile.path

SUBDIRS+=	acsvc
SUBDIRS+=	alloc
SUBDIRS+=	atomic
SUBDIRS+=	bitflag
SUBDIRS+=	bsearch
SUBDIRS+=	crc
SUBDIRS+=	dynarray
SUBDIRS+=	fmt
SUBDIRS+=	fmtstr
SUBDIRS+=	hashtbl
SUBDIRS+=	heap
SUBDIRS+=	list
SUBDIRS+=	lock
SUBDIRS+=	mlock
SUBDIRS+=	multiwait
SUBDIRS+=	mutex
SUBDIRS+=	prsig
SUBDIRS+=	rwlock
SUBDIRS+=	setprocesstitle
SUBDIRS+=	sig
SUBDIRS+=	vbitmap
SUBDIRS+=	waitlist
SUBDIRS+=	waitq

include ${PFLMK}
