# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		timecrc
SRCS=		timecrc.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/crc.c
SRCS+=		${PFL_BASE}/psc_util/log.c

include ${PFLMK}
