# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		setprocesstitle_test
SRCS+=		setprocesstitle_test.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/setprocesstitle.c

include ${PFLMK}
