# $Id$

include ../Makefile.path

PROG=		fmtstr_test
SRCS+=		fmtstr_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

include ${PFLMK}
