# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		rpcwait-sa
SRCS+=		rpcwait-sa.c
SRCS+=		${PFL_BASE}/psc_util/waitq.c
SRCS+=		${PFL_BASE}/psc_util/log.c

MODULES+=	lnet-hdrs

include ${PFLMK}
