# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		vbitmap_test
SRCS+=		vbitmap_test.c
SRCS+=		${PFL_BASE}/vbitmap.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c

include ${PFLMK}
