/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Enable BGL Features */
/* #undef BGL_SUPPORT */

/* build ldiskfs as a module */
#define CONFIG_LDISKFS_FS_MODULE 1

/* enable posix acls */
#define CONFIG_LDISKFS_FS_POSIX_ACL 1

/* enable fs security */
#define CONFIG_LDISKFS_FS_SECURITY 1

/* enable extended attributes for ldiskfs */
#define CONFIG_LDISKFS_FS_XATTR 1

/* this kernel contains Red Hat 2.4.20 patches */
#define CONFIG_RH_2_4_20 1

/* kernel has cpu affinity support */
#define CPU_AFFINITY 1

/* Enable Cray XT3 Features */
/* #undef CRAY_XT3 */

/* Liblustre Can Recover */
#define ENABLE_LIBLUSTRE_RECOVERY 1

/* Use the Pinger */
#define ENABLE_PINGER 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the <asm/page.h> header file. */
#define HAVE_ASM_PAGE_H 1

/* Define to 1 if you have the <asm/types.h> header file. */
#define HAVE_ASM_TYPES_H 1

/* panic_notifier_list is atomic_notifier_head */
/* #undef HAVE_ATOMIC_PANIC_NOTIFIER */

/* Define to 1 if you have the <blkid/blkid.h> header file. */
#define HAVE_BLKID_BLKID_H 1

/* kernel expects return from shrink_cache */
/* #undef HAVE_CACHE_RETURN_INT */

/* kernel has third arg can_sleep in fs/locks.c: flock_lock_file_wait() */
/* #undef HAVE_CAN_SLEEP_ARG */

/* Define to 1 if you have the <catamount/data.h> header file. */
/* #undef HAVE_CATAMOUNT_DATA_H */

/* cond_resched found */
#define HAVE_COND_RESCHED 1

/* Define to 1 if you have the `connect' function. */
#define HAVE_CONNECT 1

/* inode_operations->follow_link returns a cookie */
#define HAVE_COOKIE_FOLLOW_LINK 1

/* cpumask_t found */
#define HAVE_CPUMASK_T 1

/* cpu_online found */
#define HAVE_CPU_ONLINE 1

/* the kernel passes struct file to direct_IO */
/* #undef HAVE_DIO_FILE */

/* Kernel has d_add_unique */
#define HAVE_D_ADD_UNIQUE 1

/* Define to 1 if you have the <endian.h> header file. */
#define HAVE_ENDIAN_H 1

/* Define to 1 if you have the <ext2fs/ext2fs.h> header file. */
#define HAVE_EXT2FS_EXT2FS_H 1

/* filemap_fdatawrite() found */
#define HAVE_FILEMAP_FDATAWRITE 1

/* Kernel exports filemap_populate */
#define HAVE_FILEMAP_POPULATE 1

/* Define to 1 if you have the <file.h> header file. */
/* #undef HAVE_FILE_H */

/* struct file_operations has flock field */
#define HAVE_F_OP_FLOCK 1

/* Define to 1 if you have the `gethostbyname'. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the `get_preemption_level' function. */
/* #undef HAVE_GET_PREEMPTION_LEVEL */

/* gfp_t found */
#define HAVE_GFP_T 1

/* kernel has grab_cache_page_nowait_gfp() */
/* #undef HAVE_GRAB_CACHE_PAGE_NOWAIT_GFP */

/* Define to 1 if you have the `inet_ntoa' function. */
#define HAVE_INET_NTOA 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* struct inode has i_alloc_sem */
#define HAVE_I_ALLOC_SEM 1

/* kernel modules need to include config.h */
#define HAVE_KERNEL_CONFIG_H 1

/* struct kiobuf has a dovary field */
/* #undef HAVE_KIOBUF_DOVARY */

/* kmem_cache_destroy(cachep) return int */
#define HAVE_KMEM_CACHE_DESTROY_INT 1

/* use libcap */
#define HAVE_LIBCAP 1

/* libefence support is requested */
/* #undef HAVE_LIBEFENCE */

/* pthreads */
#define HAVE_LIBPTHREAD 1

/* readline library is available */
#define HAVE_LIBREADLINE 1

/* libwrap support is requested */
/* #undef HAVE_LIBWRAP */

/* linux/posix_acl_xattr.h found */
#define HAVE_LINUX_POSIX_ACL_XATTR_H 1

/* Define to 1 if you have the <linux/quota.h> header file. */
#define HAVE_LINUX_QUOTA_H 1

/* Define to 1 if you have the <linux/types.h> header file. */
#define HAVE_LINUX_TYPES_H 1

/* Define to 1 if you have the <linux/unistd.h> header file. */
#define HAVE_LINUX_UNISTD_H 1

/* Define to 1 if you have the <linux/version.h> header file. */
#define HAVE_LINUX_VERSION_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* mm_inline found */
/* #undef HAVE_MM_INLINE */

/* kernel has MS_FLOCK_LOCK flag */
/* #undef HAVE_MS_FLOCK_LOCK */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define HAVE_NETINET_TCP_H 1

/* kernel has old single-device dev_set_rdonly */
/* #undef HAVE_OLD_DEV_SET_RDONLY */

/* struct page has a list field */
/* #undef HAVE_PAGE_LIST */

/* page_mapped found */
#define HAVE_PAGE_MAPPED 1

/* the kernel defines PDE */
#define HAVE_PDE 1

/* readlink returns ssize_t */
/* #undef HAVE_POSIX_1003_READLINK */

/* Enable quota support */
#define HAVE_QUOTA_SUPPORT 1

/* register_cache found */
/* #undef HAVE_REGISTER_CACHE */

/* show_task is exported */
#define HAVE_SHOW_TASK 1

/* Define to 1 if you have the `socket' function. */
#define HAVE_SOCKET 1

/* spinlock_t is defined */
/* #undef HAVE_SPINLOCK_T */

/* struct statfs has a namelen field */
#define HAVE_STATFS_NAMELEN 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strnlen' function. */
#define HAVE_STRNLEN 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/user.h> header file. */
#define HAVE_SYS_USER_H 1

/* tasklist_lock exported */
#define HAVE_TASKLIST_LOCK 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* struct file_operations has an unlock ed_ioctl field */
#define HAVE_UNLOCKED_IOCTL 1

/* Kernel has xattr_acl */
/* #undef HAVE_XATTR_ACL */

/* Define to 1 if you have the <xtio.h> header file. */
/* #undef HAVE_XTIO_H */

/* call sysio init functions */
#define INIT_SYSIO 1

/* quota_read found */
#define KERNEL_SUPPORTS_QUOTA_READ 1

/* use /dev/urandom for random data */
#define LIBLUSTRE_USE_URANDOM 1

/* use dumplog on panic */
/* #undef LNET_DUMP_ON_PANIC */

/* Max LNET payload */
#define LNET_MAX_PAYLOAD LNET_MTU

/* Report minimum OST free space */
/* #undef MIN_DF */

/* IOCTL Buffer Size */
#define OBD_MAX_IOCTL_BUFFER 8192

/* Name of package */
#define PACKAGE "lustre"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://bugzilla.lustre.org/"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Lustre"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Lustre LUSTRE_VERSION"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "lustre"

/* Define to the version of this package. */
#define PACKAGE_VERSION "LUSTRE_VERSION"

/* The size of a `unsigned long long', as computed by sizeof. */
#define SIZEOF_UNSIGNED_LONG_LONG 8

/* use tunable backoff TCP */
/* #undef SOCKNAL_BACKOFF */

/* enable zero-copy support */
#define SOCKNAL_ZC 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.4.9"

/* zap_page_range with vma parameter */
#define ZAP_PAGE_RANGE_VMA 1
