/*<<<<<<<<<<  The below prototypes are auto-generated by fillproto */

/* -*- mode: c; c-basic-offset: 8; indent-tabs-mode: nil; -*-  
 * vim:expandtab:shiftwidth=8:tabstop=8:      
 */                                                                   
int
psc_sock_write (int sock, void *buffer, int nob, int timeout);

/*
 * no comments found for this procedure
 */
int
psc_sock_read (int sock, void *buffer, int nob, int timeout);

/*<<<<<<<<<<   This is end of the auto-generated output from fillproto. */
