# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		setprocesstitle_test
SRCS+=		setprocesstitle_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/setprocesstitle.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

include ${PFLMK}
