# $Id$

include ../Makefile.path

PROG=		setprocesstitle
SRCS=		setprocesstitle.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/setprocesstitle.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

include ${PFLMK}
