# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		setprocesstitle_test
SRCS+=		setprocesstitle_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/setprocesstitle.c

include ${PFLMK}
