# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		bitflag_test
SRCS+=		bitflag_test.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/printhex.c

MODULES+=	pfl

include ${PFLMK}
