# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		prsig_test
SRCS+=		prsig_test.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/prsig.c

include ${PFLMK}
