# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		odtable
FORCE_INST=	1
MAN+=		odtable.1
SRCS=		odtable_main.c
SRCS+=		${PFL_BASE}/dynarray.c
SRCS+=		${PFL_BASE}/lockedlist.c
SRCS+=		${PFL_BASE}/vbitmap.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/crc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/odtable.c

include ${PFLMK}
