#!/bin/sh
# $Id$

reldir=$(dirname $0)
root=$(pwd)/$reldir/..

if [ $# -ne 2 ]; then
	echo "usage: $0 dir src" >&2
	exit 1
fi

dir=$1
src=$1

msg="The below prototypes are auto-generated by fillproto"

# ^C may screw things up...
trap "" INT

base=$(basename $src)
prefix=${base%.*}
hdrbase=$prefix.h
for hdr in $(find $dir -name $hdrbase); do
	if [ -e $hdr ]; then
		if grep -q -- "$msg" $hdr; then
			tmphdr=${src%.c}.h
			domv=
			if ! [ -f $tmphdr ]; then
				# Only move the header if it's
				# in a different directory.
				mv $hdr $tmphdr
				domv=1
			fi
			$root/scripts/fillproto.pl $src
			rm -f $tmphdr~
			if [ $domv ]; then
				# Move the header back if needed.
				mv $tmphdr $hdr
			fi
		fi
	fi
done
