#!/bin/sh
# $Id$
# %ISC_START_LICENSE%
# ---------------------------------------------------------------------
# Copyright 2015-2016, Google, Inc.
# Copyright 2010-2015, Pittsburgh Supercomputing Center
# All rights reserved.
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all
# copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
# --------------------------------------------------------------------
# %END_LICENSE%

usage()
{
	echo "usage: $0 rootdir makeprog localdefsmk" >&2
	exit 1
}

if getopts "" c; then
	usage
fi

if [ $# -ne 4 ]; then
	usage
fi

rootdir=$1
hasvers=$2
make=$3
localdefsmk=$4

cat <<EOF >&2
================================================================================
System compatibility probes started on `hostname`
================================================================================
EOF

{
	echo "# generated by `id -un` from `hostname` on `date`"
	cd $rootdir/compat
	$make | sort | sed '/PICKLE_HAVE_/!d' 
	echo "PICKLE_DONE=1"
} >$localdefsmk

cat <<EOF >&2
================================================================================
System compatibility probes finished on `hostname`
================================================================================
EOF
