#!/bin/sh
# $Id$

reldir=$(dirname $0)
root=$(pwd)/$reldir/..

msg="The below prototypes are auto-generated by fillproto"

# ^C can screw up your tree.
trap "" INT

for i in $(find $root -name '*.c' \! -path '*/portals/*'); do
	base=$(basename $i)
	prefix=${base%.*}
	hdrbase=$prefix.h
	for hdr in $(find $root -name $hdrbase); do
		if [ -e $hdr ]; then
			if grep -q -- "$msg" $hdr; then
				tmphdr=${i%.c}.h
				domv=
				if ! [ -f $tmphdr ]; then
					mv $hdr $tmphdr
					domv=1
				fi
				$root/scripts/fillproto.pl $i
				rm -f $tmphdr~
				if [ $domv ]; then
					mv $tmphdr $hdr
				fi
			fi
		fi
	done
done
