#!/bin/sh

dir=$1
shift

fn=$dir/.makepid
tmpfn=$dir/.makepid.$$

vsleep()
{
	perl -We "select undef, undef, undef, $1"
}

makelocked()
{
	local pid

	echo $$ > $tmpfn
	mv -n $tmpfn $fn
	[ -e $tmpfn ] || return 1
	read pid < $fn
	[ -n "$pid" ] && ps -p $pid || rm -f $fn
	return 0
}

cleanup()
{
	rm -f $tmpfn
}

trap cleanup EXIT
while makelocked; do
	vsleep .25
done

tmpfn=$fn

"$@"
