#!/bin/sh
# $Id$

# setcc: set env `CC' appropriately to avoid recusion with wrappers.

: ${CC:?not set}

newcc=$CC
for i in ${CC}; do
	if [ x"${i#CC=}" != x"$i" ]; then
		newcc=${i#CC=}
	fi
done

if [ x"$(basename $newcc)" = x"zcc" ]; then
	newcc=cc
fi

CC=$newcc exec "$@"
