#!/usr/bin/env bash
# $Id$

dir=$(dirname $0)/..
base=$(basename $dir)

# inf/advsys/update.sh
prirepo()
{
	(getrepo ssh://source/ "$@")
}

prirepo inf/arc
prirepo inf/advsys
prirepo zest


# inf/advsys/bootstrap.sh
# $Id$
set -e
dir=$(dirname $0)
cd $dir
mkdir -p inf/advsys
mv * .[a-z]* inf/advsys
git clone https://github.com/pscedu/proj.git .
./tools/update.sh


# doc
# internal
git clone ssh://source/advsys.git p
cd p
./bootstrap.sh

# open source
git clone https://github.com/pscedu/proj.git
cd proj
./tools/update.sh











set -e

echorun()
{
	echo "$@"
	"$@"
}

clone()
{
	local url=$1
	local dir=$2
	echorun mkdir .oldsvn
	echorun mv * *.[a-z] .oldsvn
	echorun git clone $url $dir
	for i in $(cd .oldsvn && find . -name local.mk); do
		cp .oldsvn/$i $i
	done
}

getrepo()
{
	local base=$1
	local name=${2//\//.}
	local dir=$2
	[ $# -eq 3 ] && dir=$3
	if cd $dir && git status; then
		git pull
	else
		clone $base/$name.git $dir
	fi
}

pubrepo()
{
	(getrepo https://github.com/pscedu "$@")
}

cd $dir
pubrepo -R proj p
cd p
pubrepo distrib/crcutil
pubrepo distrib/fstest
pubrepo distrib/fuse
pubrepo distrib/iozone
pubrepo distrib/libs3
pubrepo distrib/spiobench
pubrepo distrib/stumbleupon-tcollector
pubrepo distrib/zfs-fuse
pubrepo fio
pubrepo idxsearch
pubrepo mkidx
pubrepo psync
pubrepo sft
pubrepo slash2
pubrepo src-upd
pubrepo xopctl

for i in $dir/inf/*/update.sh; do
	[ -e $i ] && . $i
done
