#!/bin/bash
# $Id$

term=${TERM_PROG:-xterm}

warn()
{
	echo "$@" >&2
}

xscreen_usage()
{
	warn "usage: xscreen [-S] [-c cmd] [-x args] host name"
}

xscreen()
{
	local OPTIND OPTARG
	sudo=
	xtargs=
	cmd="\$SHELL"

	while getopts "c:Sx:" c; do
		case $c in
		c) cmd=$OPTARG;;
		S) sudo=sudo;;
		x) xtargs="$xtargs $OPTARG";;
		*) xscreen_usage; exit 1;;
		esac
	done
	shift $(($OPTIND - 1))

	if [ $# -lt 2 ]; then
		echo "$@"
		xscreen_usage
		exit 1
	fi

	host=$1
	shift
	name=$1
	shift
	screen="$sudo screen -A -x -R"

	scrinit='
export PSC_SYSLOG_info=1
export PSC_LOG_LEVEL=info
export PSC_LOG_FILE=/local/'$mode'.s2/log/'$name'/%t
export SHELL=/bin/bash
ulimit -n 100000
'

	if [ x"$term" != x"${term%xterm}" ]; then
		xtargs=(-xrm XTerm*allowTitleOps:false -title "${host%%.*}: $name")
	fi

	$term "${xtargs[@]}" -e ssh -t $host $screen -S $name "sh -c '$scrinit $cmd'" &
}

usage()
{
	warn "usage: $0 mode [term]"
	exit 1
}

[ $# -lt 1 ] && usage

mode=$1
shift

p=.psc.edu
t=.psc.teragrid.org

[ $# -eq 0 ] && case "$mode" in
arc)	d=/usr/local/src/p

	set --								\
	slashd:illusion1$p:$d						\
	lnrtd:firehose1.$p:$d						\
	lnrtd:firehose2.$p:$d						\
	lnrtd:firehose3.$p:$d						\
	ex:sleep:2							\
	mount_slash:firehose1.$p:$d					\
	mount_slash:firehose2.$p:$d					\
	mount_slash:firehose3.$p:$d					\
	mount_slash:lime$p:$d						\
	mount_slash:onager$p:$d						\
	mount_slash:tahini$p:$d						\
	mount_slash:tg-login1.blacklight$t:$d				\
	mount_slash:tg-login2.blacklight$t:$d				\
	ex:sleep:2							\
	sliod:tahini-100e$p:$d:'export		CTL_SOCK_FILE=/var/run/sliod.ue.sock		LNET_NETWORKS=tcp12(eth2);'		\
	sliod:tahini-100o$p:$d:'export		CTL_SOCK_FILE=/var/run/sliod.uo.sock		LNET_NETWORKS=tcp12(eth2:1);'		\
																	\
	sliod:sense0-sliod0$p:$d:'export	CTL_SOCK_FILE=/var/run/sense0-sliod0.sock	LNET_NETWORKS=tcp12(vlan100:1);'	\
	sliod:sense0-sliod1$p:$d:'export	CTL_SOCK_FILE=/var/run/sense0-sliod1.sock	LNET_NETWORKS=tcp12(vlan100:2);'	\
	sliod:sense0-sliod2$p:$d:'export	CTL_SOCK_FILE=/var/run/sense0-sliod2.sock	LNET_NETWORKS=tcp12(vlan100:3);'	\
	sliod:sense0-sliod3$p:$d:'export	CTL_SOCK_FILE=/var/run/sense0-sliod3.sock	LNET_NETWORKS=tcp12(vlan100:4);'	\
	sliod:sense0-sliod4$p:$d:'export	CTL_SOCK_FILE=/var/run/sense0-sliod4.sock	LNET_NETWORKS=tcp12(vlan100:5);'	\
	sliod:sense0-sliod5$p:$d:'export	CTL_SOCK_FILE=/var/run/sense0-sliod5.sock	LNET_NETWORKS=tcp12(vlan100:6);'	\
	sliod:sense0-sliod6$p:$d:'export	CTL_SOCK_FILE=/var/run/sense0-sliod6.sock	LNET_NETWORKS=tcp12(vlan100:7);'	\
																	\
	sliod:sense1-sliod0$p:$d:'export	CTL_SOCK_FILE=/var/run/sense1-sliod0.sock	LNET_NETWORKS=tcp12(vlan100:1);'	\
	sliod:sense1-sliod1$p:$d:'export	CTL_SOCK_FILE=/var/run/sense1-sliod1.sock	LNET_NETWORKS=tcp12(vlan100:2);'	\
	sliod:sense1-sliod2$p:$d:'export	CTL_SOCK_FILE=/var/run/sense1-sliod2.sock	LNET_NETWORKS=tcp12(vlan100:3);'	\
	sliod:sense1-sliod3$p:$d:'export	CTL_SOCK_FILE=/var/run/sense1-sliod3.sock	LNET_NETWORKS=tcp12(vlan100:4);'	\
	sliod:sense1-sliod4$p:$d:'export	CTL_SOCK_FILE=/var/run/sense1-sliod4.sock	LNET_NETWORKS=tcp12(vlan100:5);'	\
	sliod:sense1-sliod5$p:$d:'export	CTL_SOCK_FILE=/var/run/sense1-sliod5.sock	LNET_NETWORKS=tcp12(vlan100:6);'	\
	ex:sleep:1
	;;
*)	usage;;
esac

launch()
{
	set -- $(echo "$i" | sed 's/:/ /1;s/:/ /1;s/:/ /1')
	if [ x"$1" = x"ex" ]; then
		shift
		"$@"
	else
		name=$1 ; shift
		host=$1 ; shift
		dir=$1  ; shift

		xscreen -S $host -d "$dir" $mode.$name "$@"
	fi
}

hosts="$@"

for i
do
	launch $i
done
