#!/bin/bash
# $Id$

useX=0
verbose=0
xarg=()
args=()
term=${TERM_PROG:-xterm}
hostname=$(hostname)

warn()
{
	echo "$@" >&2
}

xscreen_usage()
{
	warn "usage: xscreen [-SX] [-c cmd] [-d dir] [-I init] [-x args] host name"
}

xscreen()
{
	local OPTIND OPTARG launch=0
	local sudo setcwd scrinit
	local xtargs=(${xarg[@]})
	local cmd="exec \$SHELL"

	while getopts "c:d:I:Sx:" c; do
		case $c in
		c) cmd=$OPTARG;;
		d) setcwd="cd $OPTARG && ";;
		I) scrinit=$OPTARG;;
		S) sudo=sudo;;
		X) launch=1;;
		x) xtargs+=($OPTARG);;
		*) xscreen_usage; exit 1;;
		esac
	done
	shift $(($OPTIND - 1))

	if [ $# -ne 2 ]; then
		xscreen_usage
		exit 1
	fi

	local host=$1 ; shift
	local name=$1 ; shift
	local screen="$sudo screen -A -x -R"

	if [ x"$term" != x"${term%xterm}" ]; then
		xtargs+=(-xrm XTerm*allowTitleOps:false -title "${host%%.*}: $name")
	fi

	if [ $launch -eq 1 ]; then
		$term "${xtargs[@]}" -e ssh -t $host $setcwd $screen -S $name "sh -c '$scrinit $cmd'" &
	else
		exec $screen -S $name sh -c "$scrinit $cmd"
	fi
}

usage()
{
	warn "usage: $0 [-vX] [-x termarg] mode [host[:daemon] ...]"
	exit 1
}

while getopts "vXx:" c; do
	case $c in
	v) verbose=1;;
	X) useX=1 args+=(-X);;
	x) xarg+=("$OPTARG");;
	*) usage;;
	esac
done
shift $(($OPTIND - 1))

[ $# -lt 1 ] && usage

mode=$1
shift
hosts="$@"

p=.psc.edu
t=.psc.teragrid.org

case "$mode" in
arc)	d=/local
	ud=/usr/local

	set --								\
	slashd:illusion1$p:$d						\
	lnrtd:firehose1$p:$d						\
	lnrtd:firehose2$p:$d						\
	lnrtd:firehose3$p:$d						\
	ex:sleep:2							\
	mount_slash:firehose1$p:$d					\
	mount_slash:firehose2$p:$d					\
	mount_slash:firehose3$p:$d					\
	mount_slash:tahini$p:$ud					\
	mount_slash:tg-login1.blacklight$t:$d				\
	mount_slash:tg-login2.blacklight$t:$d				\
	ex:sleep:2							\
	sliod-uo:tahini-100e$p:$ud:'export	CTL_SOCK_FILE=/var/run/sliod.ue.sock		LNET_NETWORKS="tcp12(eth2)";'	\
	sliod-ue:tahini-100o$p:$ud:'export	CTL_SOCK_FILE=/var/run/sliod.uo.sock		LNET_NETWORKS="tcp12(eth2:1)";'	\
																\
	sliod0:sense0$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense0-sliod0.sock	LNET_NETWORKS="tcp12(vlan100:1)";'	\
	sliod1:sense0$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense0-sliod1.sock	LNET_NETWORKS="tcp12(vlan100:2)";'	\
	sliod2:sense0$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense0-sliod2.sock	LNET_NETWORKS="tcp12(vlan100:3)";'	\
	sliod3:sense0$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense0-sliod3.sock	LNET_NETWORKS="tcp12(vlan100:4)";'	\
	sliod4:sense0$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense0-sliod4.sock	LNET_NETWORKS="tcp12(vlan100:5)";'	\
	sliod5:sense0$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense0-sliod5.sock	LNET_NETWORKS="tcp12(vlan100:6)";'	\
	sliod6:sense0$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense0-sliod6.sock	LNET_NETWORKS="tcp12(vlan100:7)";'	\
																\
	sliod0:sense1$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense1-sliod0.sock	LNET_NETWORKS="tcp12(vlan100:1)";'	\
	sliod1:sense1$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense1-sliod1.sock	LNET_NETWORKS="tcp12(vlan100:2)";'	\
	sliod2:sense1$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense1-sliod2.sock	LNET_NETWORKS="tcp12(vlan100:3)";'	\
	sliod3:sense1$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense1-sliod3.sock	LNET_NETWORKS="tcp12(vlan100:4)";'	\
	sliod4:sense1$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense1-sliod4.sock	LNET_NETWORKS="tcp12(vlan100:5)";'	\
	sliod5:sense1$p:$ud:'export	CTL_SOCK_FILE=/var/run/sense1-sliod5.sock	LNET_NETWORKS="tcp12(vlan100:6)";'	\
	ex:sleep:0
	;;
*)	warn "unknown mode $mode"
	exit 1;;
esac

echorun()
{
	[ $verbose -eq 1 ] && echo "$@"
	"$@"
}

launch()
{
	local j

	set -- $(echo "$1" | sed 's/:/ /1;s/:/ /1;s/:/ /1')
	if [ x"$1" = x"ex" ]; then
		if [ -n "$hosts" -a x"$2" = x"sleep" ]; then
			continue
		fi

		shift
		echorun "$@"
	else
		local name=$1 ; shift
		local host=$1 ; shift
		local dir=$1  ; shift

		if [ -n "$hosts" ]; then
			local found=0
			for j in $hosts; do
				h=${j%:*}
				d=${j#*:}
				[ x"$d" = x"$j" ] && d=$name
				if [ x"$d" == x"$name" ] &&
				    [[ x"$host" == x$h* ]]; then
					found=1
					break
				fi
			done
			[ $found -eq 1 ] || return
		fi

		if [ $useX -eq 0 -a x"$host" != x"$hostname" ]; then
			return
		fi

		echorun xscreen -S -d "$dir/src/p" -I '
		    export PSC_SYSLOG_info=1
		    export PSC_LOG_LEVEL=warn
		    export PSC_LOG_LEVEL_info=info
		    export PSC_LOG_FILE='$dir'/'$mode'.s2/log/'$name'/%t
		    export CONFIG_FILE='$dir'/'$mode'.s2/slcfg
		    export SHELL=/bin/bash
		    export GDBHISTFILE=`which '$name'`.gdbhist
		    gdb()
		    {
			tmpfile=/tmp/.gdbcmd.$RANDOM
			(echo set history save on
			 echo set history size 10000
			 echo set confirm off
			 echo set height 0
			) > $tmpfile
			    command gdb -x $tmpfile -q "$@"
		    }
		    export -f gdb
		    mkdir -p $(dirname $PSC_LOG_FILE)
		    ulimit -n 100000
		    '"$*" $host $mode.$name
	fi
}

for i; do
	launch "${args[@]}" "$i"
done
