#!/bin/bash
# $Id$

term=${TERM_PROG:-xterm}

warn()
{
	echo "$@" >&2
}

xscreen_usage()
{
	warn "usage: xscreen [-S] [-c cmd] [-X cmds] [-x args] host name"
}

xscreen()
{
	sudo=
	xtargs=
	cmd="\$SHELL"

	while getopts "c:Sx:" c; do
		case $c in
		c) cmd=$OPTARG;;
		S) sudo=sudo;;
		x) xtargs="$xtargs $OPTARG";;
		*) xscreen_usage; exit 1;;
		esac
	done
	shift $(($OPTIND - 1))

	if [ $# -lt 2 ]; then
		echo "$@"
		xscreen_usage
		exit 1
	fi

	host=$1
	shift
	name=$1
	shift
	screen="$sudo screen -A -x -R"

	scrinit='
export PSC_SYSLOG_info=1
export PSC_LOG_LEVEL=info
export PSC_LOG_FILE=/local/'$mode'.s2/log/'$name'/%t
export SHELL=/bin/bash
ulimit -n 100000
'

	if [ x"$term" != x"${term%xterm}" ]; then
		xtargs=(-xrm XTerm*allowTitleOps:false -title "${host%%.*}: $name")
	fi

	$term "${xtargs[@]}" -e ssh -t $host $screen -S $name "sh -c '$scrinit $cmd'"
}

usage()
{
	warn "usage: $0 mode [term]"
	exit 1
}

[ $# -lt 1 ] && usage

mode=$1
shift

p=.psc.edu
t=.psc.teragrid.org

[ $# -eq 0 ] && case "$mode" in
arc)	set --	slashd:illusion1$p					\
		sliod:tahini-100e$p:'export CTL_SOCK_FILE=/var/run/sliod.ue.sock LNET_NETWORKS=tcp12(eth2);'	\
		sliod:tahini-100o$p:'export CTL_SOCK_FILE=/var/run/sliod.uo.sock LNET_NETWORKS=tcp12(eth2:1);'	\
		sliod:zs6$t						\
		sliod:sense0$p						\
		sliod:sense1$p						\
		ex:sleep:2						\
		mount_slash:lime$p					\
		mount_slash:onager$p					\
		mount_slash:tg-login1.blacklight$t			\
		mount_slash:tg-login2.blacklight$t			\
		mount_slash:tahini$p
#		lnrtd
	;;
*)	usage;;
esac

launch()
{
	set -- $(echo "$i" | sed 's/:/ /1;s/:/ /1')
	if [ x"$1" = x"ex" ]; then
		shift
		"$@"
	else
		name=$1
		shift
		host=$1
		shift
		xscreen -S $host $mode.$name "$@"
	fi
}

hosts="$@"

for i
do
	launch $i
done
