# $Id$

include ../Makefile.path

LIBRARY=	${LNET_BASE}/lib/libcfs.a
SRCS=		debug.c
SRCS+=		nidstrings.c
SRCS+=		user-lock.c
SRCS+=		user-prim.c
INCLUDES+=	-I${LNET_BASE}/include

TARGET=		${LIBRARY}

include ${LLMK}
