# $Id$

include ../Makefile.path

PROG=		pthread_test
SRCS+=		pthread_test.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/pthrutil.c

MODULES+=	pthread

include ${PFLMK}
