# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		odtable
MAN+=		odtable.1
SRCS=		odtable_test.c
SRCS+=		${PFL_BASE}/psc_ds/dynarray.c
SRCS+=		${PFL_BASE}/psc_ds/vbitmap.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/crc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/odtable.c
SRCS+=		${PFL_BASE}/psc_util/strlcpy.c

include ${PFLMK}
