.\" $Id$
.\" %PSC_START_COPYRIGHT%
.\" -----------------------------------------------------------------------------
.\" Copyright (c) 2009-2011, Pittsburgh Supercomputing Center (PSC).
.\"
.\" Permission to use, copy, and modify this software and its documentation
.\" without fee for personal use or non-commercial use within your organization
.\" is hereby granted, provided that the above copyright notice is preserved in
.\" all copies and that the copyright and this permission notice appear in
.\" supporting documentation.  Permission to redistribute this software to other
.\" organizations or individuals is not permitted without the written permission
.\" of the Pittsburgh Supercomputing Center.  PSC makes no representations about
.\" the suitability of this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\" -----------------------------------------------------------------------------
.\" %PSC_END_COPYRIGHT%
.Dd May 27, 2011
.Dt ODTABLE 1
.ds volume PSC \- Administrator's Manual
.Os http://www.psc.edu/
.Sh NAME
.Nm odtable
.Nd on-disk data storage table management utility
.Sh SYNOPSIS
.Nm odtable
.Bk -words
.Op Fl Ccos
.Op Fl e Ar elem_size
.Op Fl f Ar #frees
.Op Fl n Ar #puts
.Op Fl z Ar table_size
.Ek
.Bk -words
.Ar table_file
.Ek
.Sh DESCRIPTION
The
.Nm
utility creates and manipulates on-disk data storage tables.
The default behavior loads, scans, and displays summary information
about the specified odtable.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl C
Create a new table.
.It Fl c
Enable
.Tn CRC
checks on data stored in the table.
.It Fl e Ar elem_size
Set the entry size of elements to be stored in the odtable.
Defaults to 128 bytes.
.It Fl f Ar #frees
Clear out the given number of elements
.Ar #frees
from the beginning of the odtable.
.It Fl n Ar #puts
Store the given number of test elements
.Ar #puts
in the odtable.
.It Fl o
By default,
.Nm
will refuse overwrite of an existing file.
This option will force an overwrite.
.It Fl s
Show each entry in the odtable.
Note that this is really only a test mode to be used in conjunction with
.Fl n .
.It Fl z Ar table_size
Specify the number of entries a new table will be created with.
Defaults to
.Li 128 * 1024
slots.
.El
.Sh SEE ALSO
.Xr hexdump 1
