# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		list_test
SRCS+=		list_test.c
SRCS+=		${PFL_BASE}/listcache.c
SRCS+=		${PFL_BASE}/lockedlist.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/list.c
SRCS+=		${PFL_BASE}/log.c
SRCS+=		${PFL_BASE}/subsys.c
SRCS+=		${PFL_BASE}/waitq.c

include ${PFLMK}
