# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

TEST=		list_test
SRCS+=		list_test.c
SRCS+=		${PFL_BASE}/psc_ds/listcache.c
SRCS+=		${PFL_BASE}/psc_ds/lockedlist.c
SRCS+=		${PFL_BASE}/psc_util/alloc.c
SRCS+=		${PFL_BASE}/psc_util/init.c
SRCS+=		${PFL_BASE}/psc_util/list.c
SRCS+=		${PFL_BASE}/psc_util/log.c
SRCS+=		${PFL_BASE}/psc_util/waitq.c

include ${PFLMK}
