# $Id$

ROOTDIR=../../..
include ${ROOTDIR}/Makefile.path

PROG=		base64_test
SRCS+=		base64_test.c
SRCS+=		${PFL_BASE}/alloc.c
SRCS+=		${PFL_BASE}/base64.c
SRCS+=		${PFL_BASE}/init.c
SRCS+=		${PFL_BASE}/log.c

include ${PFLMK}
