# $Id$

ROOTDIR=../..
include ${ROOTDIR}/Makefile.path

SUBDIRS+=	base64
SUBDIRS+=	daemon
SUBDIRS+=	lnrtctl
SUBDIRS+=	lnrtd
SUBDIRS+=	odtable
SUBDIRS+=	random
SUBDIRS+=	rtgetif
SUBDIRS+=	sock
SUBDIRS+=	timecrc
SUBDIRS+=	typedump

include ${PFLMK}
